import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Banner from "../../components/banner/banner";
import NavBar from "../../components/nav/navBar";
import Card from "../../components/card/card";
import SectionCards from "../../components/card/sectionCards";
import { getVideos } from "../../lib/videos";

export default function Home() {
  const disneyVideos= getVideos();
  return (
    <>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <h2>Netflix</h2> */}
      <NavBar username="Jose" />
      <Banner
        title="clifford the red dog"
        subTitle="a very cute dog"
        imgUrl="/static/intestellar.jpg"
      />
      <div className={styles.sectionWrapper}>
        <SectionCards title="Disney" videos={disneyVideos} size="medium"/>
      </div>
    </>
  );
}
