import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Banner from "../../components/banner/banner"


export default function Home() {
  return (
    <>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2>Netflix</h2>
      <Banner title="clifford the red dog" subTitle='a very cute dog' imgUrl=""/>
    </>
  );
}
